project_id = "xznchxsbuwngfmwvsvhq"

[functions.google-sheets]
verify_jwt = false

[functions.whatsapp-alerts]
verify_jwt = false

[functions.run-saved-search]
verify_jwt = false

[functions.valo-parse]
verify_jwt = false

[functions.bob]
verify_jwt = false

[functions.bob-realtime-token]
verify_jwt = false

[functions.bob-tts]
verify_jwt = false
